name: Deploy Branches to GitHub Pages

permissions: write-all

on:
  push:
    branches:
      - spring_25
      - fall_24

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set Deployment Path
        id: setpath
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/spring_25" ]]; then
            echo "DEPLOY_PATH=linearalgebra/spring_25" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/fall_24" ]]; then
            echo "DEPLOY_PATH=linearalgebra/fall_24" >> $GITHUB_ENV
          fi

      # Optional: Build step if needed
      # - name: Build the project
      #   run: <your build command here>

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: ${{ env.DEPLOY_PATH }}
          clean: false
